=== shiipou/simplon-2024-xml/social-network.dtd
<!ELEMENT social-network (users, posts)>

<!ELEMENT users (user*)>
<!ELEMENT posts (post*)>

<!ELEMENT user (description?, attachments?)>

<!ATTLIST user id ID #REQUIRED>
<!ATTLIST user name CDATA #REQUIRED>
<!ATTLIST user email CDATA #IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT post (content?, likes?, attachments?)>

<!ATTLIST post id ID #REQUIRED>
<!ATTLIST post owner IDREF #REQUIRED>
<!ATTLIST post parent IDREF #IMPLIED>

<!ELEMENT likes (like*) >
<!ELEMENT like EMPTY >
<!ATTLIST like id ID #REQUIRED>
<!ATTLIST like user IDREF #REQUIRED>

<!ELEMENT content (#PCDATA)>

<!ELEMENT attachments (attachment*)>

<!ELEMENT attachment EMPTY>
<!ATTLIST attachment id ID #REQUIRED>
<!ATTLIST attachment type (image|post) #REQUIRED>
<!ATTLIST attachment link CDATA #IMPLIED>
<!ATTLIST attachment post IDREF #IMPLIED>

=== shiipou/simplon-2024-xml/social-network.xml
<?xml version="1.0"?>
<!DOCTYPE social-network SYSTEM "social-network.dtd">
<social-network>
    <users>
        <user id="user-1" name="Jean Marc" email="jm@example.com">
            <description>
                Ma Bio!
                Blablabla
            </description>
        </user>
        <user id="user-2" name="Tom"></user>
    </users>
    <posts>
        <post id="post-1" owner="user-1">
            <content>
                Mon post!
                blabla
            </content>
            <likes>
                <like id="like-post-1-user-1" user="user-1" />
                <like id="like-post-1-user-2" user="user-2" />
            </likes>
            <attachments>
                <attachment id="attachment-1" type="image" link="https://preview.redd.it/radion-an-internet-radio-cli-client-written-in-bash-v0-bf28wvpwjync1.png?auto=webp&amp;s=5ea01b080358157f0d8b19962b541b742a89d9b0" />
            </attachments>
        </post>
        <post id="post-2" owner="user-1">
            <content>
                I loved it !
            </content>
            <likes>
                <like id="like-post-2-user-1" user="user-1" />
                <like id="like-post-2-user-2" user="user-2" />
            </likes>
            
            <attachments>
                <attachment id="attachment-2" type="post" post="post-1" />
            </attachments>
        </post>
    </posts>
</social-network>
